{!! Theme::partial('banner-one') !!}
{!! Theme::partial('gallery-one') !!}
{!! Theme::partial('section-growth') !!}
{!! Theme::partial('ecosystem') !!}
{!! Theme::partial('services-one') !!}
{!! Theme::partial('tokenimics-ultility') !!}
{!! Theme::partial('testimonial-one') !!}
{!! Theme::partial('partner') !!}
{!! Theme::partial('journal-one') !!}
{!! Theme::partial('award-one') !!}
{!! Theme::partial('stats-one') !!}
{!! Theme::partial('partner-section') !!}
{!! Theme::partial('post-section') !!}
{!! Theme::partial('download-section') !!}